### ISSUE TITLE
file path error on OS X 10.10

### ISSUE THREAD

**Issue by idamantium** [SojournerOctocat/save-that-tweet#6]
Running the script in OS X 10.10 throws a file path error:

error "File alias Ida's Paisley Tie:Users:idabenedetto:Documents:filepath.txt of «script» wasn’t found." number -43

![screen shot 2015-03-21 at 3 31 27 pm](https://cloud.githubusercontent.com/assets/3105103/6766513/6251c06e-cfdf-11e4-813c-51be772df7e3.jpg)

**Comment by SojournerOctocat** [comment]
Oooh! Thanks! You're supposed to create the file, but I should explain that in the ReadMe. I think I will edit the script to create the file if it doesn't exist.

**Comment by SojournerOctocat** [comment]
Okay! Updated script to create the file (now named CollectedTweets.txt) if it doesn't already exist.
